[package]
name = "c-flat"
version = "0.1.0"
edition = "2024"

[dependencies]
inkwell = { version = "0.7.1", features = ["llvm21-1"] }
llvm-sys = { version = "211.0.0", features = ["prefer-dynamic"] }
colored = "3.0"
indexmap = "2.13.0"